services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./server:/app  # Монтируем текущую директорию для разработки
      - ./server/cfg:/app/cfg:z
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:8080"  # Порт для разработки
    command: ["flask", "run", "--host=0.0.0.0", "--port=8080"]
    networks:
      - radio_network
    # Добавляем возможность отладки
    tty: true
    stdin_open: true

  frontend:
    image: nginx:alpine
    volumes:
      - ./client:/usr/share/nginx/html:z
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro,z
      - ./nginx-logs:/var/log/nginx:z
    ports:
      - "8080:80"  # Порт для разработки frontend
    depends_on:
      - backend
    networks:
      - radio_network
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    # Добавляем healthcheck для nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  cfg:
  nginx-logs:

networks:
  radio_network:
    driver: bridge