services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./server/cfg:/app/cfg:z
    restart: always
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    networks:
      - radio_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - radio_network

volumes:
  radio_data:

networks:
  radio_network:
    driver: bridge