# Backend Dockerfile
FROM python:3.13-slim

# Установка рабочей директории
WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Копирование зависимостей
COPY server/requirements.txt .

# Установка зависимостей
RUN pip install --no-cache-dir -r requirements.txt watchdog

# Копирование исходного кода
#COPY server/app.py .
#COPY server/config.py .

# Создание директории для конфигурационных файлов
RUN mkdir -p cfg && \
    chmod 777 cfg

# Установка параметров для отладки
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Запускаем Flask в режиме разработки
CMD ["flask", "run", "--host=0.0.0.0", "--port=8080", "--reload"]